{ pkgs, ... }:
let
  nixPathsZsh = ''
    # Auto-generated by nix-home. Do not edit.
    export NIX_FZF_SHARE="${pkgs.fzf}/share/fzf"
    export NIX_ZSH_AUTOSUGGESTIONS="${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
    export NIX_ZSH_SYNTAX_HIGHLIGHTING="${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
    export NIX_ZSH_POWERLEVEL10K="${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme"
  '';
in
{
  # ZDOTDIR + sops 環境変数読み込み
  home.file.".zshenv".source = ../../home/dot_config/zsh/zshenv;

  # Nix store パスを環境変数としてエクスポート (Nix 評価時に生成)
  home.file.".config/zsh/nix-paths.zsh".text = nixPathsZsh;

  # .zshrc 本体 (nix-paths.zsh を source して Nix パスを参照)
  home.file.".config/zsh/.zshrc".source = ../../home/dot_config/zsh/zshrc.zsh;

  # 静的設定ファイル
  home.file.".config/zsh/.p10k.zsh".source = ../../home/dot_config/zsh/p10k.zsh;
  home.file.".config/zsh/aliases.zsh".source = ../../home/dot_config/zsh/aliases.zsh;
  home.file.".config/zsh/functions.zsh".source = ../../home/dot_config/zsh/functions.zsh;
}
