#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
NIX_HOME_REPO_ROOT=$(cd "$SCRIPT_DIR/../../.." && pwd)
TARGET_SERVERS=(asana notion)
GLOBAL_CLAUDE_MEM_MCP_SERVER="${NIX_HOME_GLOBAL_CLAUDE_MEM_MCP_SERVER:-${NIX_HOME_GLOBAL_CLAUDE_CONFIG_DIR:-$HOME/.config/claude}/plugins/marketplaces/thedotmack/plugin/scripts/mcp-server.cjs}"

resolve_project_root() {
  if [ -n "${NIX_HOME_MCP_PROJECT_DIR:-}" ]; then
    (cd "$NIX_HOME_MCP_PROJECT_DIR" && pwd -P)
    return 0
  fi

  if command -v git >/dev/null 2>&1 && git -C "$PWD" rev-parse --show-toplevel >/dev/null 2>&1; then
    git -C "$PWD" rev-parse --show-toplevel
    return 0
  fi

  pwd -P
}

resolve_project_config_base() {
  if [ -n "${NIX_HOME_MCP_PROJECT_STATE_DIR:-}" ]; then
    case "$NIX_HOME_MCP_PROJECT_STATE_DIR" in
      /*) printf '%s\n' "$NIX_HOME_MCP_PROJECT_STATE_DIR" ;;
      *) printf '%s\n' "$PROJECT_ROOT/$NIX_HOME_MCP_PROJECT_STATE_DIR" ;;
    esac
    return 0
  fi

  if command -v git >/dev/null 2>&1 && git -C "$PROJECT_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    local git_dir_abs
    git_dir_abs="$(git -C "$PROJECT_ROOT" rev-parse --absolute-git-dir)"
    printf '%s\n' "$git_dir_abs/nix-home-mcp"
    return 0
  fi

  printf '%s\n' "$PROJECT_ROOT/.nix-home/mcp"
}

PROJECT_ROOT="$(resolve_project_root)"
PROJECT_CONFIG_BASE="$(resolve_project_config_base)"
PROJECT_CLAUDE_CONFIG_DIR="$PROJECT_CONFIG_BASE/claude"
PROJECT_CODEX_HOME="$PROJECT_CONFIG_BASE/codex"
PROJECT_GEMINI_CLI_HOME="$PROJECT_CONFIG_BASE/gemini"
PROJECT_ENV_FILE="$PROJECT_ROOT/.nix-home/mcp-project.env"

usage() {
  cat <<'EOF'
Usage:
  mcp_asana_notion.sh on
  mcp_asana_notion.sh off
  mcp_asana_notion.sh status
  mcp_asana_notion.sh login
  mcp_asana_notion.sh paths
EOF
}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

csv_to_lines() {
  local raw="${1:-}"
  local item

  IFS=',' read -r -a items <<<"$raw"
  for item in "${items[@]}"; do
    item="$(trim "$item")"
    if [ -n "$item" ]; then
      printf '%s\n' "$item"
    fi
  done
}

csv_add_tokens() {
  local base="$1"
  shift
  {
    csv_to_lines "$base"
    while [ "$#" -gt 0 ]; do
      printf '%s\n' "$1"
      shift
    done
  } | awk '!seen[$0]++' | paste -sd, -
}

csv_remove_tokens() {
  local base="$1"
  shift
  local remove_csv

  remove_csv=$(IFS=,; printf '%s' "$*")
  csv_to_lines "$base" | awk -v remove="$remove_csv" '
    BEGIN {
      n = split(remove, arr, ",")
      for (i = 1; i <= n; i++) {
        if (arr[i] != "") {
          drop[arr[i]] = 1
        }
      }
    }
    !drop[$0] && !seen[$0]++ { print }
  ' | paste -sd, -
}

run_make_mcp() {
  local force_enabled="$1"
  local force_disabled="$2"

  mkdir -p "$PROJECT_CLAUDE_CONFIG_DIR" "$PROJECT_CODEX_HOME" "$PROJECT_GEMINI_CLI_HOME"
  write_project_env_file

  (
    cd "$NIX_HOME_REPO_ROOT"
    env \
      CLAUDE_CONFIG_DIR="$PROJECT_CLAUDE_CONFIG_DIR" \
      CODEX_HOME="$PROJECT_CODEX_HOME" \
      GEMINI_CLI_HOME="$PROJECT_GEMINI_CLI_HOME" \
      CLAUDE_MEM_MCP_SERVER="$GLOBAL_CLAUDE_MEM_MCP_SERVER" \
      NIX_HOME_MCP_DEFAULT_ENABLED=0 \
      NIX_HOME_MCP_FORCE_ENABLED="$force_enabled" \
      NIX_HOME_MCP_FORCE_DISABLED="$force_disabled" \
      make mcp
  )
}

run_with_project_env() {
  env \
    CLAUDE_CONFIG_DIR="$PROJECT_CLAUDE_CONFIG_DIR" \
    CODEX_HOME="$PROJECT_CODEX_HOME" \
    GEMINI_CLI_HOME="$PROJECT_GEMINI_CLI_HOME" \
    CLAUDE_MEM_MCP_SERVER="$GLOBAL_CLAUDE_MEM_MCP_SERVER" \
    "$@"
}

write_project_env_file() {
  mkdir -p "$(dirname "$PROJECT_ENV_FILE")"
  cat > "$PROJECT_ENV_FILE" <<EOF
# Generated by ok-mcp-toggle
export CLAUDE_CONFIG_DIR="$PROJECT_CLAUDE_CONFIG_DIR"
export CODEX_HOME="$PROJECT_CODEX_HOME"
export GEMINI_CLI_HOME="$PROJECT_GEMINI_CLI_HOME"
export CLAUDE_MEM_MCP_SERVER="$GLOBAL_CLAUDE_MEM_MCP_SERVER"
EOF
}

print_paths() {
  echo "project_root: $PROJECT_ROOT"
  echo "claude_config_dir: $PROJECT_CLAUDE_CONFIG_DIR"
  echo "codex_home: $PROJECT_CODEX_HOME"
  echo "gemini_cli_home: $PROJECT_GEMINI_CLI_HOME"
  echo "env_file: $PROJECT_ENV_FILE"
}

print_status() {
  local gemini_enablement="$PROJECT_GEMINI_CLI_HOME/.gemini/mcp-server-enablement.json"
  local server

  print_paths
  echo
  echo "== codex =="
  if command -v codex >/dev/null 2>&1; then
    for server in "${TARGET_SERVERS[@]}"; do
      local output enabled
      output="$(run_with_project_env codex mcp get "$server" --json 2>/dev/null || true)"
      if [ -z "$output" ]; then
        echo "$server: missing"
        continue
      fi

      if command -v jq >/dev/null 2>&1; then
        enabled="$(printf '%s' "$output" | jq -r 'if has("enabled") then (.enabled | tostring) else "unknown" end' 2>/dev/null || true)"
        [ -n "$enabled" ] || enabled="unknown"
      else
        enabled="configured"
      fi
      echo "$server: enabled=$enabled"
    done
  else
    echo "codex command not found"
  fi

  echo
  echo "== claude =="
  if command -v claude >/dev/null 2>&1; then
    for server in "${TARGET_SERVERS[@]}"; do
      if run_with_project_env claude mcp get "$server" >/dev/null 2>&1; then
        echo "$server: present"
      else
        echo "$server: absent"
      fi
    done
  else
    echo "claude command not found"
  fi

  echo
  echo "== gemini =="
  if [ -f "$gemini_enablement" ] && command -v jq >/dev/null 2>&1; then
    for server in "${TARGET_SERVERS[@]}"; do
      echo "$server: enabled=$(jq -r --arg name "$server" '
        if has($name) then
          if (.[$name] | type) == "object" and (.[$name] | has("enabled")) then
            (.[$name].enabled | tostring)
          else
            "unknown"
          end
        else
          "true"
        end
      ' "$gemini_enablement")"
    done
  else
    echo "enablement file or jq not found: $gemini_enablement"
  fi
}

run_login() {
  local server

  write_project_env_file

  if ! command -v codex >/dev/null 2>&1; then
    echo "[warn] codex command not found; skip OAuth login"
    return 0
  fi

  for server in "${TARGET_SERVERS[@]}"; do
    echo "== codex mcp login $server =="
    run_with_project_env codex mcp login "$server"
  done
}

MODE="${1:-}"

if [ -z "$MODE" ]; then
  usage
  exit 1
fi

CURRENT_FORCE_ENABLED="${NIX_HOME_MCP_FORCE_ENABLED:-jina,claude-mem}"
CURRENT_FORCE_DISABLED="${NIX_HOME_MCP_FORCE_DISABLED:-}"

case "$MODE" in
  on)
    NEW_FORCE_ENABLED="$(csv_add_tokens "$CURRENT_FORCE_ENABLED" asana notion)"
    NEW_FORCE_DISABLED="$(csv_remove_tokens "$CURRENT_FORCE_DISABLED" asana notion)"
    run_make_mcp "$NEW_FORCE_ENABLED" "$NEW_FORCE_DISABLED"
    echo
    echo "[done] asana/notion enabled (project-scoped policy applied)"
    echo "[next] start AI CLI from project shell: source \"$PROJECT_ENV_FILE\""
    ;;
  off)
    NEW_FORCE_ENABLED="$(csv_remove_tokens "$CURRENT_FORCE_ENABLED" asana notion)"
    run_make_mcp "$NEW_FORCE_ENABLED" "$CURRENT_FORCE_DISABLED"
    echo
    echo "[done] asana/notion removed from project force-enabled list"
    echo "[next] start AI CLI from project shell: source \"$PROJECT_ENV_FILE\""
    ;;
  status)
    print_status
    ;;
  login)
    run_login
    ;;
  paths)
    write_project_env_file
    print_paths
    ;;
  *)
    usage
    exit 1
    ;;
esac
